title: Pieter-Jan
author:
  name: piinghel
  email: pjinghelbrecht@gmail.com
  avatar: "/assets/avatar/profile_pic.jpg"


description: >
  Systematic trading and data science things.

theme: minima

sass:
  style: compressed
  load_paths:
    - assets/css

classes: wide


plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: classic

# Add MathJax support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
