# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          "A Jekyll theme"
description:      "A brazen two-column Jekyll theme that pairs a prominent sidebar with uncomplicated content. Made by @mdo."
url:              "https://piinghel.github.io"
baseurl:          "" # Leave empty for root

author:
  name:           "Pieter-Jan Inghelbrecht"
  url:            "https://piinghel.github.io"

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           "https://github.com/piinghel/piinghel.github.io"
